apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-kanto
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokemon-kanto
  template:
    metadata:
      labels:
        app: pokemon-kanto
    spec:
      containers:
      - image: pokeapi:0.1
        name: pokemon-kanto
        ports:
        - containerPort: 3000
        env:
          - name: API_URL
            valueFrom:
              configMapKeyRef:
                name: pokemon-kanto-cm
                key: API_URL