apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-johto
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokemon-johto
  template:
    metadata:
      labels:
        app: pokemon-johto
    spec:
      containers:
      - image: pokeapi:0.1
        name: pokemon-johto
        ports:
        - containerPort: 3000
        env:
          - name: API_URL
            valueFrom:
              configMapKeyRef:
                name: pokemon-kanto-cm
                key: API_URL
          - name: POKEDEX_NAME
            valueFrom:
              configMapKeyRef:
                name: pokemon-johto-cm
                key: POKEDEX_NAME
          - name: POKEDEX_START_NUMBER
            valueFrom:
              configMapKeyRef:
                name: pokemon-johto-cm
                key: POKEDEX_START_NUMBER
          - name: POKEDEX_END_NUMBER
            valueFrom:
              configMapKeyRef:
                name: pokemon-johto-cm
                key: POKEDEX_END_NUMBER